-- ============================================================================
-- 01_schema_simple.sql
-- Finance API - Simplified Schema (Matches FinanceDbContext exactly)
-- ============================================================================
-- 
-- This script creates the schema matching exactly what's defined in
-- FinanceDbContext.cs - no extra features, just what's needed.
-- 
-- Run this instead of the complex 01-10 scripts if you want simplicity.
-- 
-- ============================================================================

BEGIN;

SET lock_timeout = '30s';
SET statement_timeout = '60s';

-- Create schema
CREATE SCHEMA IF NOT EXISTS finance;

SET search_path TO finance, public;

-- ============================================================================
-- TABLE: users
-- ============================================================================

CREATE TABLE IF NOT EXISTS finance.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash TEXT NOT NULL,
    salt VARCHAR(50) NOT NULL DEFAULT '',
    role VARCHAR(50) NOT NULL DEFAULT 'User',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT users_username_unique UNIQUE (username),
    CONSTRAINT users_email_unique UNIQUE (email)
);

-- ============================================================================
-- TABLE: categories
-- ============================================================================

CREATE TABLE IF NOT EXISTS finance.categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NULL,
    name VARCHAR(200) NOT NULL,
    color VARCHAR(20) NOT NULL DEFAULT '#2196F3',
    icon VARCHAR(100) NOT NULL DEFAULT '',
    type VARCHAR(50) NOT NULL DEFAULT 'Expense',
    merchant_aliases JSONB NOT NULL DEFAULT '[]'::jsonb,
    
    CONSTRAINT fk_categories_user_id FOREIGN KEY (user_id) 
        REFERENCES finance.users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_categories_user_id ON finance.categories(user_id);
CREATE INDEX IF NOT EXISTS idx_categories_name ON finance.categories(name);

-- ============================================================================
-- TABLE: transactions
-- ============================================================================

CREATE TABLE IF NOT EXISTS finance.transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    transaction_date TIMESTAMP WITH TIME ZONE NOT NULL,
    billing_date TIMESTAMP WITH TIME ZONE NOT NULL,
    assigned_month_date TIMESTAMP WITH TIME ZONE NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    category_id INTEGER NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'Expense',
    merchant_name VARCHAR(500) NOT NULL DEFAULT '',
    reference_number VARCHAR(100) NULL,
    card_number VARCHAR(10) NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'ILS',
    installments INTEGER NULL,
    source VARCHAR(200) NOT NULL DEFAULT '',
    notes TEXT NULL,
    branch VARCHAR(200) NULL,
    is_halves BOOLEAN NOT NULL DEFAULT FALSE,
    
    CONSTRAINT fk_transactions_user_id FOREIGN KEY (user_id) 
        REFERENCES finance.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_transactions_category_id FOREIGN KEY (category_id) 
        REFERENCES finance.categories(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON finance.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_assigned_month_date ON finance.transactions(assigned_month_date);
CREATE INDEX IF NOT EXISTS idx_transactions_user_month ON finance.transactions(user_id, assigned_month_date);
CREATE INDEX IF NOT EXISTS idx_transactions_category_id ON finance.transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_transactions_card_number ON finance.transactions(card_number);
CREATE INDEX IF NOT EXISTS idx_transactions_user_month_card ON finance.transactions(user_id, assigned_month_date, card_number);

-- ============================================================================
-- TABLE: user_settings
-- ============================================================================

CREATE TABLE IF NOT EXISTS finance.user_settings (
    user_id INTEGER PRIMARY KEY,
    date_range_type VARCHAR(50) NOT NULL DEFAULT 'month-start',
    selected_month TIMESTAMP WITH TIME ZONE NULL,
    show_halves BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT fk_user_settings_user_id FOREIGN KEY (user_id) 
        REFERENCES finance.users(id) ON DELETE CASCADE
);

-- ============================================================================
-- TABLE: bank_statements
-- ============================================================================

CREATE TABLE IF NOT EXISTS finance.bank_statements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    account_number VARCHAR(50) NOT NULL,
    statement_date TIMESTAMP WITH TIME ZONE NOT NULL,
    balance NUMERIC(18,2) NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT fk_bank_statements_user_id FOREIGN KEY (user_id) 
        REFERENCES finance.users(id) ON DELETE CASCADE,
    CONSTRAINT bank_statements_user_id_unique UNIQUE (user_id)
);

-- ============================================================================
-- TABLE: bank_statement_rows
-- ============================================================================

CREATE TABLE IF NOT EXISTS finance.bank_statement_rows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_statement_id INTEGER NOT NULL,
    balance NUMERIC(18,2) NULL,
    value_date TIMESTAMP WITH TIME ZONE NOT NULL,
    debit NUMERIC(18,2) NULL,
    credit NUMERIC(18,2) NULL,
    reference VARCHAR(100) NULL,
    description VARCHAR(500) NULL,
    action_type VARCHAR(50) NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    
    CONSTRAINT fk_bank_statement_rows_statement_id FOREIGN KEY (bank_statement_id) 
        REFERENCES finance.bank_statements(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bank_statement_rows_statement_id ON finance.bank_statement_rows(bank_statement_id);

COMMIT;

-- ============================================================================
-- END - Schema created successfully
-- ============================================================================

